export const listJobs = [
  'Full Stack Develop',
  'Backend Develop',
  'Frontend Develop',
  'Gaming Engineer',
  'Blockchain Engineer',
  'IOS Developer',
  'Android Developer',
  'Cross Platform (Mobile)',
  'Data Analyst',
  'Data Engineer',
  'Data Scient',
  'Algorithm Engineer',
  'DevOps',
  'Reliability Engineer',
  'SysOps (Cloud / Network / Database)',
  'QA/Tesing',
  'Cybersecurity Engineer',
  'Cybersecurity Analytic & Ops',
  'Solutions Engineer',
  'Systems Engineer',
  'Systems Analyst',
  'Systems Administrator',
  'Product Manager',
  'Product Owner',
]

export const seniorities = [
  'Intern',
  'Junior',
  'Middle',
  'Senior',
  'Lead',
  'Manager',
  'Director',
  'Principal',
]
